### ISSUE TITLE
Longhorn CSI test cases freeze on K8s 1.11 clusters

### ISSUE THREAD

**Issue by LLParse** [rancher/longhorn#290] opened 2018-09-17 18:02 UTC
Kubernetes version: v1.11.2 (installed with Rancher)
Longhorn version: v0.3.1-rc1
Longhorn-test versions afflicted: v0.3.0, v0.3.1-rc1

Deploy the Longhorn test pod with following arguments: 
```
args: ["-m", "csi"]
````
When `test_csi_io` runs, it will hang indefinitely after `csi-io-test` Pod is created and running. Manually testing CSI plugin on K8s 1.11 succeeds. This automated test succeeds on previous versions of Kubernetes such as 1.10

**Comment by yasker** [comment] 2018-10-18 00:48
Freeze is fixed by: https://github.com/rancher/longhorn-tests/commit/ac0673cb2a4721667c3a5cff0f7259e9f020096b

It sounds like a bug in Kubernetes. Either in python library or stream. Deal with it later.

**Comment by yasker** [comment] 2019-01-15 01:35
Cannot reproduce on Kubernetes v1.12.4

**Closed by yasker** 2019-01-15 01:35 UTC
Labels: area/driver, area/kubernetes, area/test, bug
