### ISSUE TITLE
Mount fail in Kubernetes deployment

### ISSUE THREAD

**Issue by eportico** [rancher/longhorn#31] opened 2018-02-13 16:03 UTC
I check isciadm is OK. Any idea ?

ERRO[0000] Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host 
Environment check failed: Invalid mount namespace /host/proc/1/ns/mnt, error Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt mount], output nsenter: failed to execute mount: No such file or directory
, error exit status 1

**Comment by yasker** [comment] 2018-02-13 19:00
Which OS are you using?

Longhorn bind mounts hosts' `/proc` to `/host/proc` inside the container to perform namespace change. It will use host pid 1 mount namespace to check the exists of iscsiadm on the host. This error reports that `/host/proc/1/ns/mnt` doesn't exist in the container?

**Comment by eportico** [comment] 2018-02-14 07:04
Hi @yasker I'm using rancheros

**Comment by yasker** [comment] 2018-02-14 07:46
Sorry, we haven't added the support for RancheOS yet. But it's in the roadmap. Currently we recommended Ubuntu 16.04+.

**Comment by eportico** [comment] 2018-02-14 09:54
Ooooh!

**Comment by yasker** [comment] 2018-03-14 00:56
Duplicate of https://github.com/rancher/longhorn/issues/10

**Closed by yasker** 2018-03-14 00:56 UTC

**Comment by soriyath** [comment] 2020-07-16 08:20
Installing `iscsi-initiator-utils` helps: `sudo dnf install -y iscsi-initiator-utils`

**Comment by abserari** [comment] 2020-08-16 17:35
> Installing `iscsi-initiator-utils` helps: `sudo dnf install -y iscsi-initiator-utils`

on centOS 7: `yum install -y iscsi-initiator-utils`
