### ISSUE TITLE
chart: Fail to upgrade from NodePort to Rancher Proxy

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/longhorn#340] opened 2018-11-27 02:38 UTC
Rancher has rbac to constraint user on operating pods. But everyone can operate longhorn when longhorn ui service is exposed. Need some authentication and authorization which can be inherited from rancher's rbac . And may be a basic user/password on ui etc.

I don't know whether this issue is repeat with [64](https://github.com/rancher/longhorn/issues/64).

**Comment by yasker** [comment] 2018-11-27 02:43
As in v0.3.2, Longhorn UI has been exposed behind Rancher. You will need to have the access to the project Longhorn is running to access the UI.

**Comment by BalaBalaYi** [comment] 2018-11-27 02:51
Yes i am using 0.3.2 version catalog app. And it is deployed in the default project with admin user. But nothing happend when i open the longhorn ui dashboard.  Am i misunderstanding?

**Comment by yasker** [comment] 2018-11-27 02:53
Your Rancher session was passed in. Try logout Rancher and use the same link again. You should be prompted to login Rancher first before you can use Longhorn UI.

**Comment by BalaBalaYi** [comment] 2018-11-27 03:00
I logout rancher and refresh the longhorn ui page.  But i didn't see the prompt.  
One thing i think i should mentioned is that im using vm on openstack. The link url shows on rancher is:  http://192.168.111.84:31175 (this is a private ip). And i am using http://10.255.84.115:31175 (this is a public floating ip) to visit the web.

**Comment by yasker** [comment] 2018-11-27 03:51
Oh, that's because the endpoint configuration wasn't updated during app upgrade. We need to change to use Rancher Proxy. 

@guangbochen Is there a document we can refer to to change ingress to use Rancher Proxy?

**Comment by guangbochen** [comment] 2018-11-27 05:43
nope, but user should be able to change the longhorn UI service from e.g `NodePort` to `Rancher-Proxy` in the UI directly. 
![image](https://user-images.githubusercontent.com/4569037/49060915-6de49a00-f24a-11e8-8234-e75bf678f20a.png)

**Comment by BalaBalaYi** [comment] 2018-11-27 05:46
@yasker @guangbochen Get it. Thx very much.

**Comment by yasker** [comment] 2018-11-27 19:51
@BalaBalaYi I've reproduced the issue and filed https://github.com/rancher/charts/issues/71 for it (@guangbochen). Let me know if it's not the issue you saw.

**Comment by BalaBalaYi** [comment] 2018-11-28 00:58
@yasker 
I reproduced the upgrade and the following is the logs from rancher server:
```
[main] 2018/11/28 00:55:31 Starting Tiller v2.10.0-rancher5 (tls=false)
[main] 2018/11/28 00:55:31 GRPC listening on :53000
[main] 2018/11/28 00:55:31 Probes listening on :41710
[main] 2018/11/28 00:55:31 Storage driver is ConfigMap
[main] 2018/11/28 00:55:31 Max history per release is 0
[tiller] 2018/11/28 00:55:31 getting history for release longhorn
[storage] 2018/11/28 00:55:31 getting release history for "longhorn"
[tiller] 2018/11/28 00:55:31 preparing update for longhorn
[storage] 2018/11/28 00:55:31 getting deployed releases from "longhorn" history
[storage] 2018/11/28 00:55:31 getting last revision of "longhorn"
[storage] 2018/11/28 00:55:31 getting release history for "longhorn"
[tiller] 2018/11/28 00:55:31 rendering longhorn chart using values
2018/11/28 00:55:31 info: manifest "longhorn/templates/ingress.yaml" is empty. Skipping.
2018/11/28 00:55:31 info: manifest "longhorn/templates/tls-secrets.yaml" is empty. Skipping.
[tiller] 2018/11/28 00:55:31 creating updated release for longhorn
[storage] 2018/11/28 00:55:31 creating release "longhorn.v6"
[tiller] 2018/11/28 00:55:31 performing update for longhorn
[tiller] 2018/11/28 00:55:31 executing 1 pre-upgrade hooks for longhorn
[tiller] 2018/11/28 00:55:31 hooks complete for pre-upgrade longhorn
[kube] 2018/11/28 00:55:31 building resources from updated manifest
[kube] 2018/11/28 00:55:31 checking 15 resources for changes
[kube] 2018/11/28 00:55:31 Looks like there are no changes for StorageClass "longhorn"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for ServiceAccount "longhorn-service-account"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "volumes.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "engineimages.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "nodes.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "engines.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "replicas.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for CustomResourceDefinition "settings.longhorn.rancher.io"
[kube] 2018/11/28 00:55:31 Looks like there are no changes for ClusterRole "longhorn-role"
[kube] 2018/11/28 00:55:32 Looks like there are no changes for ClusterRoleBinding "longhorn-bind"
[kube] 2018/11/28 00:55:32 Looks like there are no changes for Service "longhorn-backend"
2018/11/28 00:55:32 Cannot patch Service: "longhorn-frontend" (Service "longhorn-frontend" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP')
2018/11/28 00:55:32 Use --force to force recreation of the resource
[kube] 2018/11/28 00:55:32 error updating the resource "longhorn-frontend":
	 Service "longhorn-frontend" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
[kube] 2018/11/28 00:55:32 Looks like there are no changes for DaemonSet "longhorn-manager"
[kube] 2018/11/28 00:55:32 Looks like there are no changes for Deployment "longhorn-driver-deployer"
[kube] 2018/11/28 00:55:32 Looks like there are no changes for Deployment "longhorn-ui"
[tiller] 2018/11/28 00:55:32 warning: Upgrade "longhorn" failed: Service "longhorn-frontend" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
[storage] 2018/11/28 00:55:32 updating release "longhorn.v1"
[storage] 2018/11/28 00:55:32 updating release "longhorn.v6"
2018/11/28 00:55:32 [ERROR] AppController p-wxc9t/longhorn [helm-controller] failed with : failed to install app longhorn. Error: UPGRADE FAILED: Service "longhorn-frontend" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Comment by yasker** [comment] 2018-11-28 01:00
@BalaBalaYi Thanks. It looks like the same issue as I reproduced. We will fix it in the next release.

**Comment by LLParse** [comment] 2019-01-10 17:32
@guangbochen Thanks for adding the force flag.

We'll need to wait for a Rancher release before we can support upgrading Longhorn frontend service. AFAIK, the only way for users on *old* versions of Rancher to discover they need Rancher 2.2+ for this feature is to document it.

Rancher 1.x had the ability to limit which charts appeared based on Rancher version, this might be a nice feature to eventually add to Rancher 2.x (alas, we can't go back in time and add the feature to the older versions...)

**Comment by yasker** [comment] 2019-01-10 17:54
@LLParse yeah that makes sense. Let's wait for Rancher v2.2 release.

**Comment by yasker** [comment] 2019-01-10 23:15
@guangbochen Is there anything we can do to limit the Rancher version for charts?

**Comment by guangbochen** [comment] 2019-01-11 00:45
Unfortunately this is indeed a missing feature we need for the catalog charts, https://github.com/rancher/rancher/issues/15014, but it will only work for newer rancher version, we probably won’t do patch for those old versions, thanks.

**Comment by yasker** [comment] 2019-02-08 00:30
Force flag is fixed by https://github.com/rancher/rancher/issues/16769 , would be in Rancher 2.2

**Closed by yasker** 2019-02-08 00:30 UTC
Labels: area/deployment, bug
