### ISSUE TITLE
[Question] Resizing a volume

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/longhorn#317] opened 2018-10-29 11:41 UTC
Hi, i would like to resize a volume created with longhorn.
Is longhorn compatible with resiszing a volume ?
What is the correct procedure ?
I tried to change the pvc and restart the pod, but the pvc stays in resizing state...

From : 
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
to : 
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
and the state is now : 
```
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-29T11:20:33Z
    status: "True"
    type: Resizing
  phase: Bound
```

Could someone guide me thought this ?
Thanks you very much !!!

**Comment by Angelinsky7** [comment] 2018-10-29 13:12
i imagine that mean that longhorn doesn't support resizing ? or iam doing something bad ?

`error: persistentvolumeclaims "prometheus-server" could not be patched: persistentvolumeclaims "prometheus-server" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`

**Comment by yasker** [comment] 2018-10-29 16:01
Longhorn doesn't support resizing currently. We're tracking it as a new feature. https://github.com/rancher/longhorn/issues/17

**Comment by Angelinsky7** [comment] 2018-10-29 16:09
@yasker thanks for your feedback and sorry i should have search the feature request better...

**Comment by yasker** [comment] 2018-11-21 00:38
Duplicate of #17

**Closed by yasker** 2018-11-21 00:38 UTC
