### ISSUE TITLE
Sometimes Vm not able to boot after HA with "Missing operating system" error.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#80] opened 2016-05-16 02:37 UTC
rancher-server version - v1.1.0-dev2-rc2
longhorn version - rancher/longhorn:v0.1.0-rc6

Steps to reproduce the problem:
Had a windows VM with ROOT and DATA disk using longhorn.
Power down the host where VM is running.
After VM gets HA-ed to a different host , it is not able to boot.

<img width="853" alt="screen shot 2016-05-15 at 7 02 48 pm" src="https://cloud.githubusercontent.com/assets/4266958/15278989/41f89ea0-1ad4-11e6-80c4-fa2b3a252b6a.png">

But the next attempt to start succeeds after seeing the "Windows Error Recovery" screen

<img width="984" alt="screen shot 2016-05-15 at 7 09 20 pm" src="https://cloud.githubusercontent.com/assets/4266958/15279002/61b772fc-1ad4-11e6-8694-bf411e33ba62.png">

**Comment by sangeethah** [comment] 2016-05-17 18:54
I also see the following error when host on which the windows VM (health check not enabled) is running is powered off and on and windows VM is started:


<img width="874" alt="screen shot 2016-05-17 at 11 53 13 am" src="https://cloud.githubusercontent.com/assets/4266958/15335190/211a01da-1c26-11e6-8fbf-e0fcd3a2e306.png">

**Comment by yasker** [comment] 2016-06-17 21:31
Duplicate of #57 .

**Closed by yasker** 2016-06-17 21:31 UTC
Labels: blocker, bug
