### ISSUE TITLE
Unable to mount volume "rpc error: code = Internal desc = exit status 1"

### ISSUE THREAD

**Issue by dnauck** [rancher/longhorn#376] opened 2019-01-22 20:24 UTC
Rancher 2.1.5
K8n: v1.11.6
Host: Ubuntu 16.04.5 LTS
Docker: 17.03.3-ce, build e19b718

Sometimes a volume cannot be mounted anymore:

```
MountVolume.SetUp failed for volume "pvc-00d0fe561b5811e9" : rpc error: code = Internal desc = exit status 1
```

Example pod:
```
$ kubectl describe pod www-example-com-wordpress-wordpress-5997f8df94-mlpgk -n www-example-com
Name:               www-example-com-wordpress-wordpress-5997f8df94-mlpgk
Namespace:          www-example-com
Priority:           0
PriorityClassName:  <none>
Node:               cl1-node-1/10.7.0.41
Start Time:         Tue, 22 Jan 2019 21:18:33 +0100
Labels:             app=www-example-com-wordpress-wordpress
                    chart=wordpress-5.1.2
                    pod-template-hash=1553948950
                    release=www-example-com-wordpress
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/www-example-com-wordpress-wordpress-5997f8df94
Containers:
  wordpress:
    Container ID:   
    Image:          docker.io/bitnami/wordpress:5.0.3
    Image ID:       
    Ports:          80/TCP, 443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   http-get http://:http/wp-login.php delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/wp-login.php delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      ALLOW_EMPTY_PASSWORD:         yes
      MARIADB_HOST:                 www-example-com-wordpress-mariadb
      MARIADB_PORT_NUMBER:          3306
      WORDPRESS_DATABASE_NAME:      bitnami_wordpress
      WORDPRESS_DATABASE_USER:      bn_wordpress
      WORDPRESS_DATABASE_PASSWORD:  <set to the key 'mariadb-password' in secret 'www-example-com-wordpress-mariadb'>  Optional: false
      WORDPRESS_USERNAME:           admin
      WORDPRESS_PASSWORD:           <set to the key 'wordpress-password' in secret 'www-example-com-wordpress-wordpress'>  Optional: false
      WORDPRESS_EMAIL:              info@example.com
      WORDPRESS_FIRST_NAME:         FirstName
      WORDPRESS_LAST_NAME:          LastName
      WORDPRESS_BLOG_NAME:          User's Blog!
      WORDPRESS_TABLE_PREFIX:       wp_
    Mounts:
      /bitnami/apache from wordpress-data (rw)
      /bitnami/php from wordpress-data (rw)
      /bitnami/wordpress from wordpress-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-46zh2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  wordpress-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  www-example-com-wordpress-wordpress
    ReadOnly:   false
  default-token-46zh2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-46zh2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age   From                 Message
  ----     ------       ----  ----                 -------
  Normal   Scheduled    2m5s  default-scheduler    Successfully assigned www-example-com/www-example-com-wordpress-wordpress-5997f8df94-mlpgk to cl1-node-1
  Warning  FailedMount  110s  kubelet, cl1-node-1  MountVolume.SetUp failed for volume "pvc-00d0fe561b5811e9" : rpc error: code = Internal desc = exit status 1
  Warning  FailedMount  2s    kubelet, cl1-node-1  Unable to mount volumes for pod "www-example-com-wordpress-wordpress-5997f8df94-mlpgk_www-example-com(e3fbf5f3-1e82-11e9-a87b-000c299a5b45)": timeout expired waiting for volumes to attach or mount for pod "www-example-com"/"www-example-com-wordpress-wordpress-5997f8df94-mlpgk". list of unmounted volumes=[wordpress-data]. list of unattached volumes=[wordpress-data default-token-46zh2]
```

The longhorn manager log does not contain any information about this error.

**Comment by dnauck** [comment] 2019-01-22 20:31
csi-attacher-0 log:

```
I0122 20:26:52.501003 1 reflector.go:357] k8s.io/client-go/informers/factory.go:131: Watch close - *v1.Node total 231 items received
I0122 20:26:59.044343 1 controller.go:167] Started VA processing "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.044379 1 csi_handler.go:85] CSIHandler: processing VA "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.044396 1 csi_handler.go:136] Starting detach operation for "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.044558 1 csi_handler.go:143] Detaching "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.044745 1 csi_handler.go:456] Can't get CSINodeInfo cl1-node-1: csinodeinfo.csi.storage.k8s.io "cl1-node-1" not found
I0122 20:26:59.044999 1 connection.go:235] GRPC call: /csi.v0.Controller/ControllerUnpublishVolume
I0122 20:26:59.045015 1 connection.go:236] GRPC request: volume_id:"pvc-00d0fe561b5811e9" node_id:"cl1-node-1"
I0122 20:26:59.053308 1 connection.go:238] GRPC response:
I0122 20:26:59.053470 1 connection.go:239] GRPC error: <nil>
I0122 20:26:59.053554 1 csi_handler.go:312] Detached "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.053844 1 util.go:71] Marking as detached "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.064604 1 util.go:82] Finalizer removed from "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.064651 1 csi_handler.go:156] Fully detached "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.064671 1 csi_handler.go:101] CSIHandler: finished processing "csi-ec2753318856bc493809094af0b93bad6999a89b386754e3d2a36c50eeeada02"
I0122 20:26:59.067552 1 controller.go:197] Started PV processing "pvc-00d0fe561b5811e9"
I0122 20:26:59.067633 1 csi_handler.go:353] CSIHandler: processing PV "pvc-00d0fe561b5811e9"
I0122 20:26:59.067647 1 csi_handler.go:357] CSIHandler: processing PV "pvc-00d0fe561b5811e9": no deletion timestamp, ignoring
I0122 20:27:06.029457 1 controller.go:197] Started PV processing "pvc-45d3cd4c112f11e9"
I0122 20:27:06.029516 1 csi_handler.go:353] CSIHandler: processing PV "pvc-45d3cd4c112f11e9"
I0122 20:27:06.029628 1 csi_handler.go:389] CSIHandler: processing PV "pvc-45d3cd4c112f11e9": VA "csi-81294f7b9708f6fb5ef534be1e9b3e6c7f61cfe48f9a7436b04337cd9f695a00" found
I0122 20:27:06.036777 1 controller.go:197] Started PV processing "pvc-2a1c677a112d11e9"
```

longhorn-csi-plugins:
```
time="2019-01-22T20:18:36Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-2a1c677a112d11e9\" "
time="2019-01-22T20:18:36Z" level=warning msg="DeleteVolume: volume pvc-2a1c677a112d11e9 not exists"
time="2019-01-22T20:18:48Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-00d0fe561b5811e9\" target_path:\"/var/lib/kubelet/pods/e3fbf5f3-1e82-11e9-a87b-000c299a5b45/volumes/kubernetes.io~csi/pvc-00d0fe561b5811e9/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_attributes:<key:\"baseImage\" value:\"\" > volume_attributes:<key:\"fromBackup\" value:\"\" > volume_attributes:<key:\"numberOfReplicas\" value:\"3\" > volume_attributes:<key:\"staleReplicaTimeout\" value:\"30\" > volume_attributes:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1547838897749-8081-rancher.io/longhorn\" > "
E0122 20:18:48.479998 1 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-00d0fe561b5811e9 /var/lib/kubelet/pods/e3fbf5f3-1e82-11e9-a87b-000c299a5b45/volumes/kubernetes.io~csi/pvc-00d0fe561b5811e9/mount
Output: mount: special device /dev/longhorn/pvc-00d0fe561b5811e9 does not exist
E0122 20:18:48.484978 1 mount_linux.go:495] format of disk "/dev/longhorn/pvc-00d0fe561b5811e9" failed: type:("ext4") target:("/var/lib/kubelet/pods/e3fbf5f3-1e82-11e9-a87b-000c299a5b45/volumes/kubernetes.io~csi/pvc-00d0fe561b5811e9/mount") options:(["defaults"])error:(exit status 1)
E0122 20:18:48.485053 1 utils.go:100] GRPC error: rpc error: code = Internal desc = exit status 1
time="2019-01-22T20:18:49Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-7ebd02851bce11e9\" target_path:\"/var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7ebd02851bce11e9/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_attributes:<key:\"baseImage\" value:\"\" > volume_attributes:<key:\"fromBackup\" value:\"\" > volume_attributes:<key:\"numberOfReplicas\" value:\"3\" > volume_attributes:<key:\"staleReplicaTimeout\" value:\"30\" > volume_attributes:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1547838897749-8081-rancher.io/longhorn\" > "
E0122 20:18:49.195604 1 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-7ebd02851bce11e9 /var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7ebd02851bce11e9/mount
Output: mount: special device /dev/longhorn/pvc-7ebd02851bce11e9 does not exist
E0122 20:18:49.200423 1 mount_linux.go:495] format of disk "/dev/longhorn/pvc-7ebd02851bce11e9" failed: type:("ext4") target:("/var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7ebd02851bce11e9/mount") options:(["defaults"])error:(exit status 1)
E0122 20:18:49.200488 1 utils.go:100] GRPC error: rpc error: code = Internal desc = exit status 1
time="2019-01-22T20:18:50Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-7eb60f6d1bce11e9\" target_path:\"/var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7eb60f6d1bce11e9/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_attributes:<key:\"baseImage\" value:\"\" > volume_attributes:<key:\"fromBackup\" value:\"\" > volume_attributes:<key:\"numberOfReplicas\" value:\"3\" > volume_attributes:<key:\"staleReplicaTimeout\" value:\"30\" > volume_attributes:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1547838897749-8081-rancher.io/longhorn\" > "
E0122 20:18:50.419607 1 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-7eb60f6d1bce11e9 /var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7eb60f6d1bce11e9/mount
Output: mount: special device /dev/longhorn/pvc-7eb60f6d1bce11e9 does not exist
E0122 20:18:50.424450 1 mount_linux.go:495] format of disk "/dev/longhorn/pvc-7eb60f6d1bce11e9" failed: type:("ext4") target:("/var/lib/kubelet/pods/e8056c70-1bd7-11e9-b009-000c2958f9e1/volumes/kubernetes.io~csi/pvc-7eb60f6d1bce11e9/mount") options:(["defaults"])error:(exit status 1)
E0122 20:18:50.424505 1 utils.go:100] GRPC error: rpc error: code = Internal desc = exit status 1
time="2019-01-22T20:18:50Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-45d3cd4c112f11e9\" "
time="2019-01-22T20:18:51Z" level=warning msg="DeleteVolume: volume pvc-45d3cd4c112f11e9 not exists"
time="2019-01-22T20:18:51Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-2a1c677a112d11e9\" "
time="2019-01-22T20:18:51Z" level=warning msg="DeleteVolume: volume pvc-2a1c677a112d11e9 not exists"
time="2019-01-22T20:18:51Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-45a4a706112f11e9\" "
time="2019-01-22T20:18:51Z" level=warning msg="DeleteVolume: volume pvc-45a4a706112f11e9 not exists"
time="2019-01-22T20:19:06Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-45d3cd4c112f11e9\" "
time="2019-01-22T20:19:06Z" level=warning msg="DeleteVolume: volume pvc-45d3cd4c112f11e9 not exists"
time="2019-01-22T20:19:06Z" level=info msg="ControllerServer delete volume req: volume_id:\"pvc-45a4a706112f11e9\" "
time="2019-01-22T20:19:06Z" level=warning msg="DeleteVolume: volume pvc-45a4a706112f11e9 not exists"
```

**Comment by dnauck** [comment] 2019-01-22 20:32
It is also on the same node, that was rebooted before. see #375

**Comment by dnauck** [comment] 2019-01-23 07:44
This is also not self-healing. I need to kill the pod and start it again to get it eventually fixed.

**Comment by yasker** [comment] 2019-01-23 17:50
@dnauck The volume is in the attached state? If so, not self-healing is a problem. Manager log would be helpful for investigating what's going on in the self-healing part.

**Comment by dnauck** [comment] 2019-01-23 18:58
The longhorn manager log does not contain any information about this error.

The volume was detached

**Comment by yasker** [comment] 2019-02-04 22:18
I think it's the same issue as #375. The CSI plugin log shows the mount code cannot find the device. And that's because the device wasn't automatically attached after the node reboots.

Mark as duplicate of #375

**Closed by yasker** 2019-02-04 22:18 UTC
Labels: area/driver, bug
