### ISSUE TITLE
Windows VM not able to boot after host was powered off and on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/longhorn#96] opened 2016-05-18 02:32 UTC
rancher-server version - v1.1.0-dev2-rc2
longhorn version - rancher/longhorn:v0.1.0

Steps to reproduce the problem:
Had a windows VM running .
Powered down the host on which the windows VM (health check not enabled) is running .
Powered on the host.
This windows VM starts up, but is not able to boot:

<img width="874" alt="screen shot 2016-05-17 at 11 53 13 am" src="https://cloud.githubusercontent.com/assets/4266958/15335190/211a01da-1c26-11e6-8fbf-e0fcd3a2e306.png">

When I restart the VM/ delete the VM (so that a new VM gets deployed) , I see the same error .

**Comment by yasker** [comment] 2016-06-17 21:37
Duplicate of #80

**Closed by yasker** 2016-06-17 21:37 UTC
Labels: blocker, bug, duplicate
