### ISSUE TITLE
tgt: kernel panic

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#234] opened 2016-11-04 04:06 UTC
[ttyS1.txt](https://github.com/rancher/longhorn/files/570585/ttyS1.txt)

**Comment by yasker** [comment] 2016-11-04 04:28
```
[ 8148.770293] BUG: unable to handle kernel NULL pointer dereference at 0000000000000040
[ 8148.773570] IP: [<ffffffff8128e1f4>] sysfs_do_create_link_sd.isra.2+0x34/0xb0
[ 8148.776541] PGD 2885e067 PUD 225b7067 PMD 0 
[ 8148.778445] Oops: 0000 [#1] SMP 
[ 8148.779575] Modules linked in: xt_nat xt_tcpudp veth rfcomm ipt_MASQUERADE nf_nat_masquerade_ipv4 xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc aufs vmw_vsock_vmci_transport vsock bnep snd_ens1371 coretemp snd_ac97_codec gameport ac97_bus crct10dif_pclmul snd_pcm crc32_pclmul vmw_balloon aesni_intel snd_seq_midi aes_x86_64 snd_seq_midi_event lrw gf128mul glue_helper snd_rawmidi ablk_helper cryptd snd_seq btusb btrtl btbcm btintel input_leds joydev snd_seq_device serio_raw snd_timer bluetooth snd soundcore i2c_piix4 shpchp vmw_vmci nfit 8250_fintek mac_hid ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi parport_pc ppdev lp parport autofs4 vmw_pvscsi vmxnet3 hid_generic usbhid hid psmouse vmwgfx ttm drm_kms_helper syscopyarea mptspi sysfillrect ahci mptscsih sysimgblt fb_sys_fops libahci mptbase drm e1000 scsi_transport_spi pata_acpi fjes
[ 8148.812550] CPU: 2 PID: 87785 Comm: kworker/u256:4 Tainted: G        W       4.4.0-45-generic #66-Ubuntu
[ 8148.814788] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 07/02/2015
[ 8148.818362] Workqueue: events_unbound async_run_entry_fn
[ 8148.819995] task: ffff88003c822940 ti: ffff880005178000 task.ti: ffff880005178000
[ 8148.821784] RIP: 0010:[<ffffffff8128e1f4>]  [<ffffffff8128e1f4>] sysfs_do_create_link_sd.isra.2+0x34/0xb0
[ 8148.824230] RSP: 0018:ffff88000517bd18  EFLAGS: 00010246
[ 8148.825617] RAX: 0000000000000000 RBX: 0000000000000040 RCX: 0000000000000001
[ 8148.827802] RDX: 0000000000000001 RSI: 0000000000000040 RDI: ffffffff821d0750
[ 8148.829642] RBP: ffff88000517bd40 R08: ffff880023c53e90 R09: ffffffff813f39ec
[ 8148.831332] R10: ffffea0000287e00 R11: 000000000000002b R12: 0000000000000001
[ 8148.832900] R13: ffffffff81cd0b6e R14: ffff880010fc7860 R15: ffff8800348b5480
[ 8148.834765] FS:  0000000000000000(0000) GS:ffff88007b680000(0000) knlGS:0000000000000000
[ 8148.836831] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 8148.838320] CR2: 0000000000000040 CR3: 0000000025a34000 CR4: 00000000003406e0
[ 8148.840198] Stack:
[ 8148.840744]  ffff8800232c9000 ffff8800232c9080 ffff8800232c900c ffff88001c785a50
[ 8148.842817]  ffff8800348b5480 ffff88000517bd50 ffffffff8128e295 ffff88000517bdb8
[ 8148.845364]  ffffffff813d3da0 ffff8800232c9000 008000200517bd78 ffff8800232c9000
[ 8148.848181] Call Trace:
[ 8148.848778]  [<ffffffff8128e295>] sysfs_create_link+0x25/0x40
[ 8148.850251]  [<ffffffff813d3da0>] add_disk+0x200/0x490
[ 8148.851580]  [<ffffffff815c8675>] sd_probe_async+0x115/0x1d0
[ 8148.853102]  [<ffffffff810a3328>] async_run_entry_fn+0x48/0x150
[ 8148.855469]  [<ffffffff8109a3e5>] process_one_work+0x165/0x480
[ 8148.857426]  [<ffffffff8109a74b>] worker_thread+0x4b/0x4c0
[ 8148.859173]  [<ffffffff8109a700>] ? process_one_work+0x480/0x480
[ 8148.861217]  [<ffffffff8109a700>] ? process_one_work+0x480/0x480
[ 8148.863029]  [<ffffffff810a0928>] kthread+0xd8/0xf0
[ 8148.864795]  [<ffffffff810a0850>] ? kthread_create_on_node+0x1e0/0x1e0
[ 8148.867118]  [<ffffffff81831c4f>] ret_from_fork+0x3f/0x70
[ 8148.869129]  [<ffffffff810a0850>] ? kthread_create_on_node+0x1e0/0x1e0
[ 8148.871232] Code: 7c 48 85 ff 74 77 55 48 89 e5 41 57 41 56 41 55 41 54 49 89 fe 53 48 c7 c7 50 07 1d 82 48 89 f3 41 89 cc 49 89 d5 e8 1c 34 5a 00 <48> 8b 1b 48 85 db 74 08 48 89 df e8 5c c2 ff ff 48 c7 c7 50 07 
[ 8148.880166] RIP  [<ffffffff8128e1f4>] sysfs_do_create_link_sd.isra.2+0x34/0xb0
[ 8148.882273]  RSP <ffff88000517bd18>
[ 8148.883186] CR2: 0000000000000040
[ 8148.884329] ---[ end trace 0ab16655133ca773 ]---
```

Duplicate of #233

**Closed by yasker** 2016-11-04 04:28 UTC
