### ISSUE TITLE
Update documentation of backup to S3 and minio yaml

### ISSUE THREAD

**Issue by lnikell** [rancher/longhorn#279] opened 2018-09-05 21:16 UTC
We should have more information about backup to S3 option, because existing docs are not enough to get it up and running. 

`kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/backupstores/minio-backupstore.yaml`

- If you run the script above configuration will cause crashing of rancher UI. It should be I guess creation of Deployment rather than a single pod.
- No namespace for service
- I think there is no need of creating two secrets, just one in the namespace the same as longhorn placed 
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UuZGVmYXVsdDo5MDAw # http://minio-service.default:9000
---
# same secret for longhorn-system namespace
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UuZGVmYXVsdDo5MDAw # http://minio-service.default:9000
```
- Add to the documentation what to do if the bucket name is not `backupbucket`, because container with minio have cmd which also depends on the bucketname
```
mkdir -p /storage/{{your bucket name}} && exec /usr/bin/minio server /storage
```
- Ideally add example of required permission policies for AWS IAM User

After debuging and fixes I was able to set up minio and connect it to longhorn without getting errors in UI, but backups still does not work for me and I see the following error in minio logs when I try to create a backup:

```
API: SYSTEM()
Time: 21:00:12 UTC 09/05/2018
Error: file not found
```

**Comment by yasker** [comment] 2018-09-05 21:58
Hi @lnikell 

The yaml file is an one-click example. And it should work well. We're running it in our test every day.

1. It should create a pod instead of a deployment. That's by design. Rancher UI may have bugs which cannot make service select one pod instead of a deployment.
2. The namespace is the default namespace, as we assumed in the `AWS_ENDPOINTS`.
3. We need to create two secrets here because if you remove Longhorn, you may not want to remove the backupstore with it (since it's the secondary storage). So one secret in the namespace for Minio, another one for Longhorn.
4. As I said, it's an example. We can provide further instructions for customization, but things like change default namespace or bucket name are not essential for this example to work.
5. Yeah, we can add more docs for IAM permissions.

I don't know how your modified version of yaml looks like and how you adjusted the parameters, so there is no way for me to tell what's wrong with your setup.

**Comment by yasker** [comment] 2018-09-06 18:09
@lnikell The bucket name doesn't need to be globally unique since we're using Minio and specified AWS_ENDPOINT in the secret.

Yeah, Minio will be installed in the default namespace, which has one minio-secret for it to read the credentials. Longhorn will use the duplicated minio-secret in the `longhorn-system` namespace to access the Minio in the default namespace. This is pure local setup. Longhorn is not accessing the S3 or internet for this.

**Comment by lnikell** [comment] 2018-09-06 20:07
@yasker mmm don't understand how does it depend on Minio. maybe I don't understand how does it work. 
The story is in AWS S3 you can't call your bucket as "backupbucket" because all s3 names are globally unique in AWS, if someone created "backupbucket" you can't create S3 with the same name. That's why in the example would be great to add the notes about how to use the a different from "backupbucket" name.

so in command s3://backupbucket@us-east-1/backupstore we have "backupbucket" which is the name of the bucket in your AWS as I understand. If you create a name such for a bucket in S3 such as "backup.rancher.com" for example then you will need to put s3://backup.rancher.com@us-east-1/backupstore but also script will not work because in script there is hardcoded bucket name.

**Comment by yasker** [comment] 2018-09-06 20:09
@lnikell Minio is a storage solution with S3 APi. https://minio.io/

**Comment by lnikell** [comment] 2018-09-06 21:50
@yasker thank you! I was confused with documentation a bit, made improvements and created new PR with the example of a configuration for AWS S3 and required permissions set.

Thank you for helping me understand how should it be.

**Comment by yasker** [comment] 2018-09-07 20:54
Fixed by #280

**Closed by yasker** 2018-09-07 20:54 UTC
Labels: doc

**Comment by ainiml** [comment] 2019-11-17 02:27
> Hi @yasker,
> 
> > The yaml file is an one-click example. And it should work well. We're running it in our test every day.
> 
> The problem I see is that part of the documentation
> ![image](https://user-images.githubusercontent.com/2697570/45142886-f6a6e900-b1b9-11e8-9cbb-4e49b7148a27.png)
> Users can't leave and use it as it is because s3 buckets are globally unique, so people can't name it as `backupbucket`. My first assumption was that I could change the bucket name to whatever I want, but it did not work, because it also require changes in that line https://github.com/rancher/longhorn/blob/master/deploy/backupstores/minio-backupstore.yaml#L36
> So without creating dir with my bucket name it does not work. Maybe I'm doing something wrong.
> `mkdir -p /storage/backupbucket`
> 
> 1. Not sure that I understand it :). Based on example script it, minio pod will be installed to default namespace, the same namespace will get the first minio-secret. It will be used for initialization of the pod. Am I right that Longhorn as well use the direct access to the s3 and require the same secret?

How do you format the backup s3 in Longhorn for a minio server running in Rancher?

**Comment by voarsh2** [comment] 2022-03-05 19:15
Can someone explain why this was made as a pod? I have to recreate it as a Deployment so I can change config easily.... e.g. storage location.
