### ISSUE TITLE
UI: snapshot tree: system generated snapshot should be hidden by default

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#497] opened 2019-04-23 21:56 UTC
If `Create By User` is false, the snapshot should be hidden by default. It should be only revealed if `Show System Hidden` is chosen.

Once it's revealed, it should be shown different from `removed=true` snapshots or user-created snapshots. The user won't be allowed to `revert` to it, but unlike removed snapshot, `delete` is allowed for the system created snapshots once it's revealed.

**Comment by meldafrawi** [comment] 2019-04-26 20:19
`Show System Hidden` stopped working after page reload,

![Screenshot from 2019-04-26 22-11-46](https://user-images.githubusercontent.com/18232258/56833953-61538480-6870-11e9-8188-c77c0a534dbf.png)


![Screenshot from 2019-04-26 22-15-30](https://user-images.githubusercontent.com/18232258/56834119-d32bce00-6870-11e9-96e8-5f914deca032.png)


**Steps to reproduce this behavior:**
- create pod using 
`kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml`
- delete replica, to generate a snapshot with `Created By User`: false,
- reload the page.

**Result:**
`Show System Hidden` stopped working.

**Comment by smallteeths** [comment] 2019-04-28 05:44
@meldafrawi I followed your steps, but the bug did not recur. May I ask if the version of UI is the latest? This is the address of my project http://3.19.64.160:32175/volume/pvc-03f90a2c-695b-11e9-85c9-063587d8a228

**Comment by meldafrawi** [comment] 2019-04-29 17:34
@smallteeths
I'm using latest longhorn-ui images exited on docker hub
  `image: rancher/longhorn-ui:241599b`

**Comment by yasker** [comment] 2019-04-29 17:40
@meldafrawi Can you re-test with the latest Longhorn UI? Just run `make` with https://github.com/rancher/longhorn-ui to get the latest image built.

**Comment by meldafrawi** [comment] 2019-04-29 17:54
I've built a new Longhorn UI image, and re-tested.
The issue is resolved.
I'm closing the issue.

**Closed** 2019-04-29 17:55 UTC
Labels: area/ui
