### ISSUE TITLE
panic during teardown test

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#245] opened 2016-11-10 04:32 UTC
Panic during teardown test:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x9a93a0, 0xc420012090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/longhorn/app.revertSnapshot(0xc42008fa40, 0xc4201c5af8, 0x48d941)
	/go/src/github.com/rancher/longhorn/app/snapshot.go:96 +0x106
github.com/rancher/longhorn/app.SnapshotRevertCmd.func1(0xc42008fa40)
	/go/src/github.com/rancher/longhorn/app/snapshot.go:48 +0x2f
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.Run(0xa2eae3, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:179 +0xbbe
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420076b00, 0xc42008f7c0, 0x0, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/app.go:307 +0x9fb
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.startApp(0xa30154, 0x9, 0xa2f92c, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:261 +0x7ac
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.Command.Run(0xa30154, 0x9, 0xa2f92c, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/command.go:70 +0x16a3
github.com/rancher/longhorn/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200769a0, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/longhorn/vendor/github.com/codegangsta/cli/app.go:196 +0xc00
main.longhornCli()
	/go/src/github.com/rancher/longhorn/main.go:77 +0x5a4
main.main()
	/go/src/github.com/rancher/longhorn/main.go:24 +0xac
2016-11-09 02:22:27.703768: iteration = 461 thread = 4 : Device ready after 0.000 seconds
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "longhorn-tests/stress/teardown-test.py", line 162, in run_test
    check_data(thread, pattern1)
  File "longhorn-tests/stress/teardown-test.py", line 77, in check_data
    assert ord(data[0]) == pattern
AssertionError
```
Controller logs:
```
sheng@ubuntu:~$ docker logs 79
time="2016-11-09T10:14:13Z" level=info msg="Starting with replicas [\"tcp://172.18.1.4:9502\" \"tcp://172.18.2.4:9502\"]" 
time="2016-11-09T10:14:13Z" level=info msg="Connecting to remote: 172.18.1.4:9502" 
time="2016-11-09T10:14:13Z" level=info msg="Opening: 172.18.1.4:9502" 
time="2016-11-09T10:14:13Z" level=info msg="Adding backend: tcp://172.18.1.4:9502" 
time="2016-11-09T10:14:13Z" level=info msg="Connecting to remote: 172.18.2.4:9502" 
time="2016-11-09T10:14:13Z" level=info msg="Opening: 172.18.2.4:9502" 
time="2016-11-09T10:14:13Z" level=info msg="Adding backend: tcp://172.18.2.4:9502" 
time="2016-11-09T10:14:15Z" level=info msg="SCSI device /dev/sdf created" 
time="2016-11-09T10:14:15Z" level=info msg="Creating device /dev/longhorn/vol4 8:80" 
time="2016-11-09T10:14:15Z" level=info msg="Device /dev/longhorn/vol4 is ready" 
time="2016-11-09T10:14:15Z" level=info msg="Listening on localhost:9501" 
time="2016-11-09T10:17:55Z" level=info msg="Snapshot: 172.18.2.4:9502 dc6f3557-a8be-4c24-8f76-6e4ac35e0661" 
time="2016-11-09T10:17:55Z" level=info msg="Snapshot: 172.18.1.4:9502 dc6f3557-a8be-4c24-8f76-6e4ac35e0661" 
127.0.0.1 - - [09/Nov/2016:10:17:55 +0000] "POST /v1/volumes/dm9sNA==?action=snapshot HTTP/1.1" 200 180
sheng@ubuntu:~$ docker exec 79 launch snapshot ls
ID
dc6f3557-a8be-4c24-8f76-6e4ac35e0661
sheng@ubuntu:~$ docker exec 79 launch snapshot revert dc6f3557-a8be-4c24-8f76-6e4ac35e0661
sheng@ubuntu:~$ docker exec 79 launch snapshot ls
ID
dc6f3557-a8be-4c24-8f76-6e4ac35e0661
```

**Comment by yasker** [comment] 2016-11-14 22:46
Duplicate of #240

**Closed by yasker** 2016-11-14 22:46 UTC
Labels: duplicate
