### ISSUE TITLE
rebuild-test fails on first read after snapshot

### ISSUE THREAD

**Issue by sheng-liang** [rancher/longhorn#260] opened 2016-12-19 21:32 UTC
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "rebuild-test.py", line 184, in read_write
    write_data(thread, index, pattern2)
  File "rebuild-test.py", line 70, in write_data
    writeat_direct("/dev/longhorn/vol%d" % (thread), index * PAGE_SIZE, str(chr(pattern))*PAGE_SIZE)
  File "rebuild-test.py", line 59, in writeat_direct
    pg_data = readat_direct(dev, pg_offset, PAGE_SIZE)
  File "rebuild-test.py", line 43, in readat_direct
    ret = directio.read(f, to_read)
OSError: [Errno 5] Input/output error

**Comment by yasker** [comment] 2016-12-20 01:53
It seems caused by EOF returned by replica.

```
time="2016-12-20T01:44:40Z" level=info msg="Starting with replicas [\"tcp://172.18.1.6:9502\" \"tcp://172.18.2.6:9502\"]" 
time="2016-12-20T01:44:40Z" level=info msg="Connecting to remote: 172.18.1.6:9502" 
time="2016-12-20T01:44:40Z" level=info msg="Opening: 172.18.1.6:9502" 
time="2016-12-20T01:44:40Z" level=info msg="Adding backend: tcp://172.18.1.6:9502" 
time="2016-12-20T01:44:40Z" level=info msg="Connecting to remote: 172.18.2.6:9502" 
time="2016-12-20T01:44:40Z" level=info msg="Opening: 172.18.2.6:9502" 
time="2016-12-20T01:44:40Z" level=info msg="Adding backend: tcp://172.18.2.6:9502" 
time="2016-12-20T01:44:46Z" level=info msg="SCSI device /dev/sdf created" 
time="2016-12-20T01:44:46Z" level=info msg="Device /dev/longhorn/vol6 is ready" 
time="2016-12-20T01:44:46Z" level=info msg="Listening on localhost:9501" 
time="2016-12-20T01:44:47Z" level=error msg="Error reading from wire: EOF" 
time="2016-12-20T01:44:47Z" level=error msg="Setting replica tcp://172.18.2.6:9502 to ERR due to: EOF" 
time="2016-12-20T01:44:47Z" level=error msg="Ignoring error because tcp://172.18.1.6:9502 is mode RW: tcp://172.18.2.6:9502: EOF" 
time="2016-12-20T01:44:47Z" level=info msg="Snapshot: 172.18.1.6:9502 9c8a5bc0-b783-48f9-abf4-3ffcaed59d5f" 
127.0.0.1 - - [20/Dec/2016:01:44:47 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:48Z" level=info msg="Removing backend: tcp://172.18.2.6:9502" 
time="2016-12-20T01:44:48Z" level=info msg="Closing: 172.18.2.6:9502" 
127.0.0.1 - - [20/Dec/2016:01:44:48 +0000] "DELETE /v1/replicas/dGNwOi8vMTcyLjE4LjIuNjo5NTAy HTTP/1.1" 0 0
time="2016-12-20T01:44:48Z" level=info msg="Snapshot: 172.18.1.6:9502 b5d57374-6fc3-4f98-99c1-ae773028a9b9" 
127.0.0.1 - - [20/Dec/2016:01:44:48 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:49Z" level=info msg="Connecting to remote: 172.18.2.6:9502" 
time="2016-12-20T01:44:49Z" level=info msg="Opening: 172.18.2.6:9502" 
time="2016-12-20T01:44:49Z" level=info msg="Snapshot: 172.18.1.6:9502 0da51bdb-c2e4-4b28-a6e1-41ac656078d4" 
time="2016-12-20T01:44:49Z" level=info msg="Snapshot: 172.18.2.6:9502 0da51bdb-c2e4-4b28-a6e1-41ac656078d4" 
127.0.0.1 - - [20/Dec/2016:01:44:49 +0000] "POST /v1/replicas HTTP/1.1" 200 196
time="2016-12-20T01:44:49Z" level=info msg="Adding backend: tcp://172.18.2.6:9502" 
time="2016-12-20T01:44:50Z" level=info msg="Snapshot: 172.18.2.6:9502 555325b2-9abd-4eaf-b6aa-03fa0a775366" 
time="2016-12-20T01:44:50Z" level=info msg="Snapshot: 172.18.1.6:9502 555325b2-9abd-4eaf-b6aa-03fa0a775366" 
127.0.0.1 - - [20/Dec/2016:01:44:50 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:52Z" level=info msg="Snapshot: 172.18.1.6:9502 3058b810-4eca-4e61-b7e5-c3c6715f0f36" 
time="2016-12-20T01:44:52Z" level=info msg="Snapshot: 172.18.2.6:9502 3058b810-4eca-4e61-b7e5-c3c6715f0f36" 
127.0.0.1 - - [20/Dec/2016:01:44:52 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
127.0.0.1 - - [20/Dec/2016:01:44:53 +0000] "PUT /v1/replicas/dGNwOi8vMTcyLjE4LjIuNjo5NTAy HTTP/1.1" 200 196
time="2016-12-20T01:44:53Z" level=info msg="Snapshot: 172.18.2.6:9502 583e3d7a-528e-4a0d-8245-682e5e10b9d1" 
time="2016-12-20T01:44:53Z" level=info msg="Snapshot: 172.18.1.6:9502 583e3d7a-528e-4a0d-8245-682e5e10b9d1" 
127.0.0.1 - - [20/Dec/2016:01:44:53 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:55Z" level=info msg="Snapshot: 172.18.2.6:9502 63241b9b-5831-4db9-8a19-945000a9ed88" 
time="2016-12-20T01:44:55Z" level=info msg="Snapshot: 172.18.1.6:9502 63241b9b-5831-4db9-8a19-945000a9ed88" 
127.0.0.1 - - [20/Dec/2016:01:44:55 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:57Z" level=info msg="Snapshot: 172.18.2.6:9502 273d9392-e167-492b-b7dd-c9e15d2c6af0" 
time="2016-12-20T01:44:57Z" level=info msg="Snapshot: 172.18.1.6:9502 273d9392-e167-492b-b7dd-c9e15d2c6af0" 
127.0.0.1 - - [20/Dec/2016:01:44:57 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:44:59Z" level=info msg="Snapshot: 172.18.2.6:9502 380083ff-e385-4fa1-9ee8-cc99d13def74" 
time="2016-12-20T01:44:59Z" level=info msg="Snapshot: 172.18.1.6:9502 380083ff-e385-4fa1-9ee8-cc99d13def74" 
127.0.0.1 - - [20/Dec/2016:01:44:59 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:45:02Z" level=error msg="Error reading from wire: EOF" 
time="2016-12-20T01:45:02Z" level=info msg="Snapshot: 172.18.2.6:9502 c2e137cc-ccbf-4887-9613-b5b498ff13cc" 
time="2016-12-20T01:45:02Z" level=info msg="Snapshot: 172.18.1.6:9502 c2e137cc-ccbf-4887-9613-b5b498ff13cc" 
time="2016-12-20T01:45:02Z" level=error msg="Setting replica tcp://172.18.2.6:9502 to ERR due to: Post http://172.18.1.6:9502/v1/replicas/1?action=snapshot: dial tcp 172.18.1.6:9502: getsockopt: connection refused" 
127.0.0.1 - - [20/Dec/2016:01:45:01 +0000] "POST /v1/volumes/dm9sNg==?action=snapshot HTTP/1.1" 200 180
time="2016-12-20T01:45:02Z" level=error msg="Ignoring error because tcp://172.18.1.6:9502 is mode RW: tcp://172.18.2.6:9502: Post http://172.18.1.6:9502/v1/replicas/1?action=snapshot: dial tcp 172.18.1.6:9502: getsockopt: connection refused" 
time="2016-12-20T01:45:02Z" level=error msg="Replicator.ReadAt:0 EOF" 
time="2016-12-20T01:45:02Z" level=error msg="Setting replica tcp://172.18.1.6:9502 to ERR due to: EOF" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: tcp://172.18.1.6:9502: EOF" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:02Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:03Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:03Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:03Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:03Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:03Z" level=error msg="I/O error: No backend available" 
time="2016-12-20T01:45:22Z" level=error msg="Ping retry 1 on replica http://172.18.1.6:9502/v1/replicas/1; error: Ping timeout" 
Dec 20 01:44:42.946973: ->172.18.1.6:9503 P[  0kB]      336us
Dec 20 01:44:42.950686: ->172.18.2.6:9503 P[  0kB]     1144us
Dec 20 01:44:44.947034: ->172.18.1.6:9503 P[  0kB]     2259us
Dec 20 01:44:44.950662: ->172.18.2.6:9503 P[  0kB]      527us
Dec 20 01:44:46.891249: ->172.18.2.6:9503 R[  4kB]      397us
Dec 20 01:44:46.895540: ->172.18.1.6:9503 R[  4kB]      512us
Dec 20 01:44:46.898520: ->172.18.2.6:9503 R[  4kB]      226us
Dec 20 01:44:46.904377: ->172.18.1.6:9503 R[  4kB]      216us
Dec 20 01:44:46.904809: ->172.18.2.6:9503 R[  4kB]      168us
Dec 20 01:44:46.905282: ->172.18.1.6:9503 R[  4kB]      230us
Dec 20 01:44:46.905865: ->172.18.2.6:9503 R[  4kB]      155us
Dec 20 01:44:46.906283: ->172.18.1.6:9503 R[  4kB]      146us
Dec 20 01:44:46.906641: ->172.18.2.6:9503 R[  4kB]     1246us
Dec 20 01:44:46.908303: ->172.18.1.6:9503 R[  4kB]      756us
Dec 20 01:44:46.909339: ->172.18.2.6:9503 R[  4kB]      191us
Dec 20 01:44:46.910001: ->172.18.1.6:9503 R[  4kB]      182us
Dec 20 01:44:46.910502: ->172.18.2.6:9503 R[  4kB]      246us
Dec 20 01:44:46.911059: ->172.18.1.6:9503 R[  4kB]     7232us
Dec 20 01:44:46.927768: ->172.18.2.6:9503 R[  4kB]      184us
Dec 20 01:44:46.935075: ->172.18.1.6:9503 R[  4kB]     8318us
Dec 20 01:44:46.947007: ->172.18.1.6:9503 P[  0kB]     2708us
Dec 20 01:44:46.949876: ->172.18.1.6:9503 R[  4kB]      328us
Dec 20 01:44:46.939757: ->172.18.2.6:9503 R[1024kB]    10556us
Dec 20 01:44:46.953387: ->172.18.2.6:9503 P[  0kB]      726us
Dec 20 01:44:46.957204: ->172.18.2.6:9503 R[  4kB]      247us
Dec 20 01:44:46.975185: ->172.18.1.6:9503 R[  4kB]      387us
Dec 20 01:44:47.014978: ->172.18.2.6:9503 R[  4kB]      400us
Dec 20 01:44:47.032028: ->172.18.2.6:9503 W[1024kB]        5us failed
Dec 20 01:44:47.032046: ->172.18.1.6:9503 W[1024kB]    37684us
Dec 20 01:44:47.032277: ->172.18.1.6:9503 R[  4kB]    37607us
Dec 20 01:44:47.076919: ->172.18.1.6:9503 R[  4kB]     1587us
Dec 20 01:44:47.086495: ->172.18.1.6:9503 R[  4kB]     8475us
Dec 20 01:44:47.086486: ->172.18.1.6:9503 R[1024kB]     8687us
Dec 20 01:44:47.098695: ->172.18.1.6:9503 R[  4kB]     7783us
Dec 20 01:44:47.107128: ->172.18.1.6:9503 W[1024kB]    32615us
Dec 20 01:44:47.110111: ->172.18.1.6:9503 R[  4kB]    29787us
Dec 20 01:44:47.110152: ->172.18.1.6:9503 R[ 12kB]    29750us
Dec 20 01:44:47.110302: ->172.18.1.6:9503 R[ 28kB]    29604us
Dec 20 01:44:47.110734: ->172.18.1.6:9503 R[ 72kB]    29177us
Dec 20 01:44:47.145463: ->172.18.1.6:9503 R[120kB]      452us
Dec 20 01:44:47.155925: ->172.18.1.6:9503 R[128kB]     2515us
Dec 20 01:44:47.155510: ->172.18.1.6:9503 R[1024kB]     4587us
Dec 20 01:44:47.160498: ->172.18.1.6:9503 R[128kB]      386us
Dec 20 01:44:47.169352: ->172.18.1.6:9503 R[  8kB]     1012us
Dec 20 01:44:47.169366: ->172.18.1.6:9503 R[ 16kB]     1152us
Dec 20 01:44:47.169381: ->172.18.1.6:9503 R[  4kB]     1207us
Dec 20 01:44:47.169405: ->172.18.1.6:9503 R[ 16kB]     1258us
Dec 20 01:44:47.169377: ->172.18.1.6:9503 R[ 68kB]     1290us
Dec 20 01:44:47.169241: ->172.18.1.6:9503 R[1024kB]     9539us
```

**Comment by yasker** [comment] 2016-12-22 18:45
Duplicate of #262

**Closed by yasker** 2016-12-22 18:45 UTC
